var properties = [
  {name:'前海华润金融中心',area:'qianhai',rent:'160-270',rentNote:'含税，可申请政府补贴60/40/20元/㎡',sizeRange:'160-5000',address:'前海自由贸易区梦海大道与桂湾四路交汇处',metro:'5号线桂湾站',tags:['超甲级','近地铁','品牌开发商','政府补贴'],highlights:['华润集团开发及管理，249.4m超高层','12.8米层高大堂，24部通力高速电梯','前海唯一万象城商业配套','可申请政府补贴60/40/20元/㎡','企业所得税15%优惠，总部扶持最高3000万'],img:'images/upload_1780918085500_0.jpg',developer:'华润集团',property:'华润物管',floors:'53层',contact:'15914050727'},
  {name:'前海科兴科学园',area:'xixiang',rent:'80-128',rentNote:'含税含物业',sizeRange:'169-20000',address:'宝安区西乡银田路与兴业路交汇处',metro:'11号线碧海湾站A出口',tags:['甲级','近地铁','大面积','品牌开发商'],highlights:['正中集团倾力打造，甲级品质','约11米挑高大堂，冰蓄冷中央空调24h供冷','100:1超量停车位（2800个）','使用率高达70%-75%','180度一线山海景观'],img:'images/qianhai-kexing.jpg',developer:'正中集团',property:'深圳市正中企业服务有限公司',floors:'约30层',contact:'13500000000'},
  {name:'龙光世纪大厦',area:'baoan-center',rent:'面议',rentNote:'致电咨询专属优惠',sizeRange:'600-10000',address:'宝安区宝华路与兴华路交汇处',metro:'5号线宝华地铁站',tags:['近地铁','大面积','可分割'],highlights:['紧邻地铁11号线，串联宝中/南山/福田','靠近国际会展中心，享会展经济红利','规划高品质商务公寓和办公大厦','商业配套齐全'],img:'images/longguang-shiji.jpg',developer:'龙光集团',property:'面议',floors:'面议',contact:'13500000000'},
  {name:'前海颐都大厦',area:'qianhai',rent:'面议',rentNote:'致电咨询专属优惠',sizeRange:'219-6000',address:'南山区前海深港合作区妈湾片区',metro:'1号线/2号线',tags:['近地铁','可分割','前海政策'],highlights:['前海深港合作区核心位置','多条地铁及公交环绕','配备先进办公设施及高速网络','商业配套丰富','享前海政策红利'],img:'images/qianhai-yidu.jpg',developer:'面议',property:'面议',floors:'面议',contact:'13500000000'},
  {name:'华润置地大厦',area:'nanshan-tech',rent:'面议',rentNote:'致电咨询专属优惠',sizeRange:'219-6000',address:'南山区深南大道与铜鼓路交界西北口',metro:'1号线高新园站',tags:['品牌开发商','近地铁','科技园核心'],highlights:['南山科技园核心区，华润品牌品质','地铁1/5/7号线多站覆盖','楼宇智能化系统，高效中央空调','高科技/金融/文创企业聚集'],img:'images/huarun-zhidi.jpg',developer:'华润置地',property:'华润物业',floors:'面议',contact:'13500000000'},
  {name:'前海深港基金小镇',area:'qianhai',rent:'面议',rentNote:'致电咨询专属优惠',sizeRange:'600-10000',address:'南山区桂湾四路',metro:'5号线桂湾站',tags:['金融专属','前海政策','独栋可冠名'],highlights:['前海深港合作区核心，毗邻香港','连接内地与香港金融市场的重要桥梁','建筑风格融合现代与传统','享前海先行先试改革红利'],img:'images/jijin-xiaozhen.jpg',developer:'面议',property:'面议',floors:'面议',contact:'13500000000'},
  {name:'中粮大悦城',area:'baoan-center',rent:'面议',rentNote:'致电咨询专属优惠',sizeRange:'219-6000',address:'宝安区建安一路360号',metro:'5号线兴东站',tags:['品牌开发商','配套完善','可分割'],highlights:['宝安中心区核心位置','现代商业与办公空间融合','品牌组合+艺术展览+主题活动','商务餐饮与休闲娱乐设施丰富'],img:'images/zhongliang-dayuecheng.jpg',developer:'中粮集团',property:'面议',floors:'面议',contact:'13500000000'},
  {name:'金环宇湾芯城',area:'xixiang',rent:'面议',rentNote:'致电咨询专属优惠',sizeRange:'219-2000',address:'宝安区西乡铁仔路56号',metro:'1号线西乡站',tags:['科技园区','层高优势','可分割'],highlights:['国家高新区，科技产业园区','层高4.5-6米，空间灵活','聚集信息技术/生物医药/新能源企业','3栋建筑，总建面10.7万平','478个停车位，12台电梯'],img:'images/jinhuanyu-wanxincheng.jpg',developer:'面议',property:'面议',floors:'面议',contact:'13500000000'},
  {name:'南山云科技大厦',area:'nanshan-tech',rent:'面议',rentNote:'物业费33元/㎡/月（含空调）',sizeRange:'145-2000',address:'南山区留仙洞总部基地万科云城六期',metro:'13号线石鼓站（0距离）',tags:['地铁上盖','总部地标','品牌物业'],highlights:['234米留仙洞地标建筑','地铁13号线0距离无缝连接','整层最高使用率80%','37部品牌高速电梯','万科物业高端品质管理','楼下万科里商业MALL'],img:'images/nanshan-yunkeji.jpg',developer:'万科',property:'万科物业',floors:'53层',contact:'13500000000'},
  {name:'科兴科学园',area:'nanshan-tech',rent:'面议',rentNote:'致电咨询专属优惠',sizeRange:'219-6000',address:'南山区科苑路15号',metro:'1号线高新园站/2号线科苑站',tags:['科技园标杆','近地铁','大面积'],highlights:['南山科技园核心地标','集聚AI/大数据/生物医药等高科技企业','智能楼宇系统+中央空调+高速网络','定期举办技术论坛和行业峰会','高端餐饮/酒店/购物中心配套齐全'],img:'images/kexing-kexueyuan.jpg',developer:'面议',property:'面议',floors:'面议',contact:'13500000000'}
];
